### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'pacmd'

### ISSUE THREAD

**Issue by Alan1CC** [lyrebird-voice-changer/lyrebird#112]
I've installed Lyrebird from the AUR and it didn't open when I first executed it.
Tried executing from the terminal and this is what it got me:

```
Traceback (most recent call last):
  File "/usr/share/lyrebird/app.py", line 13, in <module>
    win = mainwindow.MainWindow()
  File "/usr/share/lyrebird/app/mainwindow.py", line 62, in __init__
    utils.unload_pa_modules(check_state=False)
  File "/usr/share/lyrebird/app/core/utils.py", line 60, in unload_pa_modules
    subprocess.call('pacmd unload-module module-null-sink'.split(" "))
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pacmd'
```

If I could at the very least know where I must create this directory (I am guessing it's a directory), then that would be splendid.
Thank you and have a nice day.

**Comment by harrego** [comment]
This is related to #62 and is because you are using Pipewire instead of Pulseaudio. Lyrebird doesn't yet support Pipewire I'm afraid.
