### ISSUE TITLE
Module initialization failed Ubuntu 22.04

### ISSUE THREAD

**Issue by kn0xy** [lyrebird-voice-changer/lyrebird#125]
After downloading the .deb from wget as instructed and installing it via apt, I run lyrebird and it opens normally. However when I flip the switch to activate, I get the following message in terminal, and I cannot see the device in pavucontrol.

`[info] Starting Lyrebird v1.2.0
[info] Audio server: pulseaudio
Failure: Module initialization failed
Traceback (most recent call last):
  File "/usr/share/lyrebird/app/ui/mainwindow.py", line 179, in toggle_activated
    state.audio.load_pa_modules()
  File "/usr/share/lyrebird/app/core/audio.py", line 55, in load_pa_modules
    self.null_sink = subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pactl', 'load-module', 'module-null-sink', 'sink_name=Lyrebird-Output', 'node.description="Lyrebird', 'Output"']' returned non-zero exit status 1.`

**Comment by ErisonNull** [comment]
Same issue. Can anybody help?(

**Comment by ErfanBahramali** [comment]
Same
