### ISSUE TITLE
Couldn't install package from Aur

### ISSUE THREAD

**Issue by dennykurniawan48** [lyrebird-voice-changer/lyrebird#136]
Hi, I'm an Manjaro user.
I couldn't install this package from Aur because of conflicted software.

This is log that I get while installing lyrebird:
```
Warning: lyrebird is only available from AUR
Preparing...
Checking lyrebird dependencies...
Resolving dependencies...
Checking inter-conflicts...
Error: Failed to prepare transaction:
could not satisfy dependencies:
- removing pulseaudio breaks dependency 'pulseaudio=16.1-6' required by pulseaudio-zeroconf
```

How can I solve this problem?

**Comment by ddan39** [comment]
adjust the PKGBUILD and remove the requirement for pipewire. it isn't needed, lyrebird should work with both pipewire and pulseaudio. it is currently broken tho. if you really want to get it working right now, let me know and i'll upload my PKGBUILD with patches and pulseaudio dependency instead of pipewire.

**Comment by dennykurniawan48** [comment]
Thanks @ddan39 I could install it with removing pipewire from the dependencies, and the software could run but as you said I can't record my voice.
When I run lyrebird I got this error when turned on the toggle button:

```
Failure: Module initialization failed
Traceback (most recent call last):
  File "/usr/share/lyrebird/app/ui/mainwindow.py", line 179, in toggle_activated
    state.audio.load_pa_modules()
  File "/usr/share/lyrebird/app/core/audio.py", line 55, in load_pa_modules
    self.null_sink = subprocess.check_call(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pactl', 'load-module', 'module-null-sink', 'sink_name=Lyrebird-Output', 'node.description="Lyrebird', 'Output"']' returned non-zero exit status 1.
```

**Comment by ddan39** [comment]
yes, if you see my pull request #138 i fix that bug, plus another

**Comment by dennykurniawan48** [comment]
Sorry for my late reply, I added your pull request and build it on my computer. However I found the result of the audio output was broken, I'm using OBS studio.

These are the logs that I got:
```
[info] Starting Lyrebird v1.2.0
[info] Audio server: PulseAudio
Failure: No such entity
48
49
sox WARN rate: rate clipped 34346 samples; decrease volume?
sox WARN rate: rate clipped 13741 samples; decrease volume?
sox FAIL sox: `Lyrebird-Output' error writing to pulse audio device: Connection terminated: Operation not permitted
sox WARN rate: rate clipped 11190 samples; decrease volume?
```
